version: '3.7'

services:
  webservice:
    image: tte:1.0
    container_name: tte
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "7500:7501"
    working_dir: /home/Project/kms
    volumes:
      - .:/home/Project/kms
      - /opt/nfast:/opt/nfast:ro
      - /opt/nfast/kmdata:/opt/nfast/kmdata:rw
      - /opt/nfast/sockets:/opt/nfast/sockets
    # working_dir: ./
    build:
      context: ./
      dockerfile: Dockerfile
    # command: ["java", "-jar", "/kms7500.jar"]    
    networks:
      - pdsi
    
networks:
  pdsi:

# volumes:
#   pdsi-volume: