version: '3.7'

services:
  webservice:
    image: tte:1.0
    container_name: tte-ubuntu
    stdin_open: true
    tty: true
    # network_mode: "host"
    restart: always
    ports:
      - "7502:7501"
    working_dir: /home/Project/ubuntu
    volumes:
      - .:/home/Project/ubuntu
      - /opt/nfast:/opt/nfast:ro
      - /opt/nfast/kmdata:/opt/nfast/kmdata:rw
      - /opt/nfast/sockets:/opt/nfast/sockets
    # working_dir: ./
    build:
      context: ./
      dockerfile: Dockerfile
    # command: ["java", "-jar", "/kms7500.jar"]    
    networks:
      - pdsi-ubuntu
    
networks:
  pdsi-ubuntu:

# volumes:
#   pdsi-volume: