version: '3.7'

services:
  webservice:
    image: tte:2.0
    container_name: ubuntu-tte-01
    stdin_open: true
    tty: true
    # network_mode: "host"
    restart: always
    ports:
      - "1502:7501"
    working_dir: /home/Project/ubuntu
    volumes:
      # - .:/home/Project/ubuntu
      - /opt/nfast/kmdata:/opt/nfast/kmdata:rw
      - /opt/nfast/sockets.hwsp:/opt/nfast/sockets
    build:
      context: ./
      dockerfile: Dockerfile
    # command: ["java", "-jar", "/kms7500.jar"]    
    networks:
      - pdsi-tte01
    
networks:
  pdsi-tte01:

# volumes:
#   pdsi-volume: