version: '3.7'

services:
  webservice:
    image: tte:1.3
    container_name: tte-ubu1
    stdin_open: true
    tty: true
    # network_mode: "host"
    restart: always
    ports:
      - "1502:7501"
    working_dir: /home/Project/ubuntu
    volumes:
      - .:/home/Project/ubuntu
      - /opt/nfast/kmdata:/opt/nfast/kmdata
      - /opt/nfast/sockets.hwsp:/opt/nfast/sockets
      # - /opt/nfast:/opt/nfast:rw
      # - /opt/nfast/kmdata:/opt/nfast/kmdata:rw
      # - /opt/nfast/sockets.hwsp:/opt/nfast/sockets
    # working_dir: ./
    build:
      context: ./
      dockerfile: Dockerfile
    # command: ["java", "-jar", "/kms7500.jar"]    
    networks:
      - pdsi-tte
    
networks:
  pdsi-tte:

# volumes:
#   pdsi-volume: