version: '3.7'

services:
  ubuntu:
    container_name: ubuntu-os
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    command: ["sleep","infinity"]
    # volumes:
      # - /opt/nfast:/opt/nfast:ro
      # - /opt/nfast/kmdata:/opt/nfast/kmdata:rw
      # - /opt/nfast/sockets:/opt/nfast/sockets
    networks:
      - pdsi

  
    
networks:
  pdsi:

# volumes:
#   pdsi-volume: